config/routes.rb
Rails.application.routes.draw do
  resources :calls do
    post :generate_token, on: :collection
    post :get_caller, on: :collection
  end
  resources :contact_segments
  resources :deals
  devise_for :users
  resources :contact_sequences
  resources :sequences do
    resources :sequence_steps
  end
  resources :emails do
    post :send_email, on: :collection
    get :open, on: :member
    get :click, on: :member
    get :opt_out, on: :member
    get :opt_in, on: :member
  end
  resources :companies do
    post :import, on: :collection
  end
  resources :contacts do
    post :import, on: :collection
    resources :contact_notes
  end
  resources :contact_tags

  get 'search', to:'search#index'
  get 'inbox', to: 'inbox#index'

  scope 'settings' do
    resources :email_accounts
    resources :email_templates
    resources :api_keys    
    resources :users    
    resources :custom_fields    
    resources :stages    
    get 'import', to: 'settings#import'
  end

  namespace :api do
    namespace :v1 do
      resources :contacts
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "contacts#index"
end

app/models/sequence_step.rb
class SequenceStep < ApplicationRecord
  belongs_to :sequence
  belongs_to :parent, class_name: 'SequenceStep', optional: true
  has_many :children, class_name: 'SequenceStep', foreign_key: 'parent_id', dependent: :destroy
  has_many :contact_sequences, dependent: :nullify
  store_accessor :properties, 
    :tag, 
    :email_template_id, 
    :condition_subject, 
    :condition_operator, 
    :condition_value,
    :delay_value,
    :delay_unit

  enum delay_unit: {
    minutes: 0,
    hours: 1,
    days: 2,
  }
  enum condition_subject: {
    email_unopened: 0,
    email_opened: 1,
    asset_downloaded: 2,
    asset_not_downloaded: 3,
    page_visited: 4,
    page_not_visited: 5,
  }
  enum condition_operator: {
    equal_to: 0,
    greater_than: 1,
    less_than: 2,
    not_equal_to: 3,
    contains: 4,
    starts_with: 5,
  }
  enum action: {
    condition: 0,
    delay: 1,
    send_email: 2,
  }

  def description
    description = action.humanize + ' '
    case action
    when 'send_email'
      description += "\"#{email_template.name}\"" if !email_template.nil?
    when 'delay'
      description += delay_value + ' ' + delay_unit if delay_unit && delay_value
    end
    if action == 'condition'
      description += condition_subject
      description += condition_operator
      description += condition_value
    end
    description
  end

  def icon
    case action
      when 'send_email'
        'envelope'
      when 'delay'
        'hourglass'
      when 'condition'
        'question-circle'
    end
  end

  def email_template
    if self.email_template_id
      EmailTemplate.find(self.email_template_id)
    end
  end

end

app/controllers/sequence_steps_controller.rb
class SequenceStepsController < ApplicationController
  before_action :set_sequence, only: [:new, :create, :edit, :destroy]
  before_action :set_sequence_step, only: [:show, :edit, :update, :destroy]

  # GET /sequence_steps
  # GET /sequence_steps.json
  def index
    @sequence_steps = SequenceStep.all
  end

  # GET /sequence_steps/1
  # GET /sequence_steps/1.json
  def show
  end

  # GET /sequence_steps/new
  def new
    @sequence_step = SequenceStep.new
    @sequence_step.parent_id = params[:parent] if params[:parent]
    render partial: 'form'
  end

  # GET /sequence_steps/1/edit
  def edit
    render partial: 'form'
  end

  # POST /sequence_steps
  # POST /sequence_steps.json
  def create
    @sequence_step = @sequence.steps.build(sequence_step_params)
    @replaced_step = SequenceStep.find_by(parent_id: sequence_step_params[:parent_id].presence, path: sequence_step_params[:path])

    if @sequence_step.save
      if @replaced_step
        @replaced_step.parent_id = @sequence_step.id
        @replaced_step.save
      end
    else
      flash[:error] = @sequence_step.errors
    end
  end

  # PATCH/PUT /sequence_steps/1
  # PATCH/PUT /sequence_steps/1.json
  def update
    if @sequence_step.update(sequence_step_params)
      flash[:success] = 'Sequence step was successfully updated.'
    else
      flash[:error] = @sequence_step.errors
    end
  end

  # DELETE /sequence_steps/1
  # DELETE /sequence_steps/1.json
  def destroy
    @sequence_step.destroy
      flash[:success] = 'Sequence step was successfully destroyed.'
      redirect_to @sequence
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sequence_step
      @sequence_step = SequenceStep.find(params[:id])
    end

    def set_sequence
      @sequence = Sequence.find(params[:sequence_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sequence_step_params
      params.require(:sequence_step).permit(:parent_id, :path, :condition_subject, :condition_operator, :condition_value, :action, :object, :email_template_id, :delay_value, :delay_unit)
    end
end

app/helpers/sequence_steps_helper.rb
module SequenceStepsHelper
end

app/views/sequence_steps/_form.html.erb
<%= simple_form_for [@sequence, @sequence_step], remote: true do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :parent, as: :hidden %>
    <%= f.input :path, as: :hidden %>
    <%= f.input :action %>

    <div data-action="condition" style="<%= 'display: block;' if @sequence_step.action == 'condition' %>">
      <div class="row">
        <div class="col-md-4">
          <%= f.input :condition_subject %>      
        </div>
        <div class="col-md-4">
          <%= f.input :condition_operator %>
        </div>
        <div class="col-md-4">
          <%= f.input :condition_value %>
        </div>
      </div>      
    </div>

    <%#= f.input :tag, collection: ContactTag.all %>

    <div data-action="send_email" style="<%= 'display: block;' if @sequence_step.action == 'send_email' %>">
      <div class="row">
        <div class="col-md-12">
          <%= f.input :email_template_id, collection: EmailTemplate.all %>
        </div>
      </div>        
    </div>

    <div data-action="delay" style="<%= 'display: block;' if @sequence_step.action == 'delay' %>">
      <div class="row">
        <div class="col-md-6">
          <%= f.input :delay_value %>      
        </div>
        <div class="col-md-6">
          <%= f.input :delay_unit %>
        </div>
      </div>
    </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sequence_steps/edit.html.erb
<h1>Editing Sequence Step</h1>
<%= render 'form' %>

app/views/sequence_steps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sequence Steps</h1>

<table>
  <thead>
    <tr>
      <th>Sequence</th>
      <th>Triggered by</th>
      <th>Condition</th>
      <th>Action</th>
      <th>Object</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sequence_steps.each do |sequence_step| %>
      <tr>
        <td><%= sequence_step.sequence %></td>
        <td><%= sequence_step.triggered_by %></td>
        <td><%= sequence_step.condition %></td>
        <td><%= sequence_step.action %></td>
        <td><%= sequence_step.object %></td>
        <td><%= link_to 'Show', sequence_step %></td>
        <td><%= link_to 'Edit', edit_sequence_step_path(sequence_step) %></td>
        <td><%= link_to 'Destroy', sequence_step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sequence Step', new_sequence_step_path %>

app/views/sequence_steps/new.html.erb
<h1>New Sequence Step</h1>
<%= render 'form', sequence_step: @sequence_step %>

app/views/sequence_steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sequence:</strong>
  <%= @sequence_step.sequence %>
</p>

<p>
  <strong>Triggered by:</strong>
  <%= @sequence_step.triggered_by %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @sequence_step.condition %>
</p>

<p>
  <strong>Action:</strong>
  <%= @sequence_step.action %>
</p>

<p>
  <strong>Object:</strong>
  <%= @sequence_step.object %>
</p>

<%= link_to 'Edit', edit_sequence_step_path(@sequence_step) %> |
<%= link_to 'Back', sequence_steps_path %>