config/routes.rb
Rails.application.routes.draw do
  resources :calls do
    post :generate_token, on: :collection
    post :get_caller, on: :collection
  end
  resources :contact_segments
  resources :deals
  devise_for :users
  resources :contact_sequences
  resources :sequences do
    resources :sequence_steps
  end
  resources :emails do
    post :send_email, on: :collection
    get :open, on: :member
    get :click, on: :member
    get :opt_out, on: :member
    get :opt_in, on: :member
  end
  resources :companies do
    post :import, on: :collection
  end
  resources :contacts do
    post :import, on: :collection
    resources :contact_notes
  end
  resources :contact_tags

  get 'search', to:'search#index'
  get 'inbox', to: 'inbox#index'

  scope 'settings' do
    resources :email_accounts
    resources :email_templates
    resources :api_keys    
    resources :users    
    resources :custom_fields    
    resources :stages    
    get 'import', to: 'settings#import'
  end

  namespace :api do
    namespace :v1 do
      resources :contacts
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "contacts#index"
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :stage
  belongs_to :contact
  belongs_to :owner, class_name: "User"
  has_paper_trail only: [:stage, :status]  

  enum status: {
    won: 0,
    lost: 1,
    unqualified: 2,
    no_response: 3,
  }
  
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  # GET /deals
  # GET /deals.json
  def index
    @stages = Stage.all
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
    render partial: 'new'
  end

  # GET /deals/1/edit
  def edit
    render partial: 'edit'
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)
    if @deal.save
      flash[:success] = 'Deal was successfully created.'
      render :js => "Turbolinks.visit('#{deals_url}')"      
    else
      flash[:error] = @deal.errors.full_messages.join('<br>')
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    if @deal.update(deal_params)
      flash[:success] = 'Deal was successfully updated.'
      render :js => "Turbolinks.visit('#{deals_url}')"      
    else
      flash[:error] = @deal.errors.full_messages.join('<br>')
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    flash[:success] = 'Deal was successfully destroyed.'
    redirect_to deals_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:status, :name, :stage_id, :value, :close_date, :contact_id, :owner_id)
    end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_edit.html.erb
<h1>Editing Deal</h1>

<%= render 'form', deal: @deal %>

app/views/deals/_form.html.erb
<%= simple_form_for(@deal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-6">
        <%= f.input :name %>
        <%= f.input :value %>        
        <%= f.association :contact %>
      </div>
      <div class="col-md-6">
        <%= f.association :stage %>      
        <%= f.input :close_date %>
        <%= f.association :owner, selected: current_user.id %>        
        <% if @deal.persisted? %>
          <%= f.input :status %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/deals/_new.html.erb
<h1>New Deal</h1>

<%= render 'form', deal: @deal %>

app/views/deals/index.html.erb
<div class="page-header">
  <h1>Deals</h1>
  <div class="ml-auto mr-3">
   
  </div>
</div>

<% @stages.each do |stage| %>
  <div class="stage">
    <div class="stage-name d-flex">
      <h3><%= stage.name %></h3>
      <div class="stage-total ml-auto"><%= number_to_currency stage.deals.sum(:value) %> (<%= stage.deals.count %>)</div>
    </div>
    <ul class="deals">
      <% stage.deals.each do |deal| %>
        <li>
          <a href="<%= edit_deal_path(deal) %>" data-remote="true" class="modal-trigger">
            <h4><%= deal.name %> - <%= number_to_currency deal.value %></h4>
          </a>
          <a href="<%= contact_path(deal.contact) %>">
            <%= deal.contact.avatar(30).html_safe %>
            <%= deal.contact.name %>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @deal.status %>
</p>

<p>
  <strong>Name:</strong>
  <%= @deal.name %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @deal.stage %>
</p>

<p>
  <strong>Value:</strong>
  <%= @deal.value %>
</p>

<p>
  <strong>Close date:</strong>
  <%= @deal.close_date %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @deal.contact %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @deal.owner %>
</p>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>