config/routes.rb
Rails.application.routes.draw do
  resources :calls do
    post :generate_token, on: :collection
    post :get_caller, on: :collection
  end
  resources :contact_segments
  resources :deals
  devise_for :users
  resources :contact_sequences
  resources :sequences do
    resources :sequence_steps
  end
  resources :emails do
    post :send_email, on: :collection
    get :open, on: :member
    get :click, on: :member
    get :opt_out, on: :member
    get :opt_in, on: :member
  end
  resources :companies do
    post :import, on: :collection
  end
  resources :contacts do
    post :import, on: :collection
    resources :contact_notes
  end
  resources :contact_tags

  get 'search', to:'search#index'
  get 'inbox', to: 'inbox#index'

  scope 'settings' do
    resources :email_accounts
    resources :email_templates
    resources :api_keys    
    resources :users    
    resources :custom_fields    
    resources :stages    
    get 'import', to: 'settings#import'
  end

  namespace :api do
    namespace :v1 do
      resources :contacts
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "contacts#index"
end

app/models/stage.rb
class Stage < ApplicationRecord
  has_many :deals
  validates_presence_of :name
  
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  layout 'settings'  
  before_action :set_stage, only: [:show, :edit, :update, :destroy]

  # GET /stages
  # GET /stages.json
  def index
    @stages = Stage.all
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(stage_params)

    respond_to do |format|
      if @stage.save
        format.html { redirect_to @stage, notice: 'Stage was successfully created.' }
        format.json { render :show, status: :created, location: @stage }
      else
        format.html { render :new }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1
  # PATCH/PUT /stages/1.json
  def update
    respond_to do |format|
      if @stage.update(stage_params)
        format.html { redirect_to @stage, notice: 'Stage was successfully updated.' }
        format.json { render :show, status: :ok, location: @stage }
      else
        format.html { render :edit }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage.destroy
    respond_to do |format|
      format.html { redirect_to stages_url, notice: 'Stage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stage_params
      params.require(:stage).permit(:name, :win_probability)
    end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= simple_form_for(@stage) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :win_probability %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stages</h1>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Win Probability</th>
      <th>Total Deals</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stages.each do |stage| %>
      <tr>
        <td><%= stage.name %></td>
        <td><%= stage.win_probability %></td>
        <td><%= stage.deals.count %></td>
        <td>
        <%= link_to '', edit_stage_path(stage), class: 'btn btn-secondary edit' %>
        <%= link_to '', stage, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary delete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Stage', new_stage_path, class: 'btn btn-secondary btn-sm' %>

app/views/stages/new.html.erb
<h1>New Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Back', stages_path %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stage.name %>
</p>

<p>
  <strong>Win probability:</strong>
  <%= @stage.win_probability %>
</p>

<%= link_to 'Edit', edit_stage_path(@stage) %> |
<%= link_to 'Back', stages_path %>