config/routes.rb
Rails.application.routes.draw do
  resources :calls do
    post :generate_token, on: :collection
    post :get_caller, on: :collection
  end
  resources :contact_segments
  resources :deals
  devise_for :users
  resources :contact_sequences
  resources :sequences do
    resources :sequence_steps
  end
  resources :emails do
    post :send_email, on: :collection
    get :open, on: :member
    get :click, on: :member
    get :opt_out, on: :member
    get :opt_in, on: :member
  end
  resources :companies do
    post :import, on: :collection
  end
  resources :contacts do
    post :import, on: :collection
    resources :contact_notes
  end
  resources :contact_tags

  get 'search', to:'search#index'
  get 'inbox', to: 'inbox#index'

  scope 'settings' do
    resources :email_accounts
    resources :email_templates
    resources :api_keys    
    resources :users    
    resources :custom_fields    
    resources :stages    
    get 'import', to: 'settings#import'
  end

  namespace :api do
    namespace :v1 do
      resources :contacts
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "contacts#index"
end

app/models/contact_note.rb
class ContactNote < ApplicationRecord
  belongs_to :user
  belongs_to :contact, :touch => :last_acitivity_at
end

app/controllers/contact_notes_controller.rb
class ContactNotesController < ApplicationController
  before_action :set_contact_note, only: [:show, :edit, :update, :destroy]

  # GET /contact_notes
  # GET /contact_notes.json
  def index
    @contact_notes = ContactNote.all
  end

  # GET /contact_notes/1
  # GET /contact_notes/1.json
  def show
  end

  # GET /contact_notes/new
  def new
    @contact_note = ContactNote.new
  end

  # GET /contact_notes/1/edit
  def edit
  end

  # POST /contact_notes
  # POST /contact_notes.json
  def create
    @contact_note = ContactNote.new(contact_note_params)
    @contact_note.user_id = current_user.id

    if @contact_note.save
      flash[:success] = 'Contact note was successfully created.'
    else
      render json: @contact_note.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /contact_notes/1
  # PATCH/PUT /contact_notes/1.json
  def update
    respond_to do |format|
      if @contact_note.update(contact_note_params)
        format.html { redirect_to @contact_note, notice: 'Contact note was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_note }
      else
        format.html { render :edit }
        format.json { render json: @contact_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_notes/1
  # DELETE /contact_notes/1.json
  def destroy
    @contact_note.destroy
    respond_to do |format|
      format.html { redirect_to contact_notes_url, notice: 'Contact note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_note
      @contact_note = ContactNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_note_params
      params.require(:contact_note).permit(:user_id, :contact_id, :content)
    end
end

app/helpers/contact_notes_helper.rb
module ContactNotesHelper
end

app/views/contact_notes/_form.html.erb
<%= simple_form_for([@contact, @contact_note]) do |f| %>
  <%= f.error_notification %>
  <%= f.input :contact_id, input_html: {value: @contact.id}, as: :hidden  %>
  <div class="reverse-editor">  
    <%= f.trix_editor :content, label: false %>
  </div>
  <%= f.button :submit, value: 'Add note' %>
<% end %>

app/views/contact_notes/edit.html.erb
<h1>Editing Contact Note</h1>

<%= render 'form', contact_note: @contact_note %>

<%= link_to 'Show', @contact_note %> |
<%= link_to 'Back', contact_notes_path %>

app/views/contact_notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contact Notes</h1>

<table>
  <thead>
    <tr>
      <th>Contact</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_notes.each do |contact_note| %>
      <tr>
        <td><%= contact_note.contact %></td>
        <td><%= contact_note.content %></td>
        <td><%= link_to 'Show', contact_note %></td>
        <td><%= link_to 'Edit', edit_contact_note_path(contact_note) %></td>
        <td><%= link_to 'Destroy', contact_note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact Note', new_contact_note_path %>

app/views/contact_notes/new.html.erb
<h1>New Contact Note</h1>

<%= render 'form', contact_note: @contact_note %>

<%= link_to 'Back', contact_notes_path %>

app/views/contact_notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contact:</strong>
  <%= @contact_note.contact %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact_note.content %>
</p>

<%= link_to 'Edit', edit_contact_note_path(@contact_note) %> |
<%= link_to 'Back', contact_notes_path %>